name: CryptoTraderWorkflow
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Protoc action
      uses: squzy/protoc-actions@v2.0.8

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: test
      run: make test-build

    - name: Build
      run: make build-all
